//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttBaliMonth
    {
        public int PAttID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string EmpPeriod { get; set; }
        public string EmpIDB1 { get; set; }
        public Nullable<double> Days1 { get; set; }
        public string EmpIDB2 { get; set; }
        public Nullable<double> Days2 { get; set; }
        public string EmpIDB3 { get; set; }
        public Nullable<double> Days3 { get; set; }
        public string EmpIDB4 { get; set; }
        public Nullable<double> Days4 { get; set; }
        public string EmpIDB5 { get; set; }
        public Nullable<double> Days5 { get; set; }
        public string EmpIDB6 { get; set; }
        public Nullable<double> Days6 { get; set; }
        public string EmpIDB7 { get; set; }
        public Nullable<double> Days7 { get; set; }
        public string EmpIDB8 { get; set; }
        public Nullable<double> Days8 { get; set; }
        public string EmpIDB9 { get; set; }
        public Nullable<double> Days9 { get; set; }
        public string EmpIDB10 { get; set; }
        public Nullable<double> Days10 { get; set; }
    }
}
