//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttDataAppOT
    {
        public string AEmpDate { get; set; }
        public Nullable<int> AEmpID { get; set; }
        public Nullable<System.DateTime> AAttDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<short> ApprovedOT { get; set; }
        public string ShiftName { get; set; }
    }
}
