//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttMnAppOT
    {
        public int PID { get; set; }
        public int EmpID { get; set; }
        public string Period { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<short> OT1 { get; set; }
        public Nullable<short> OT2 { get; set; }
        public Nullable<short> OT3 { get; set; }
        public Nullable<short> OT4 { get; set; }
        public Nullable<short> OT5 { get; set; }
        public Nullable<short> OT6 { get; set; }
        public Nullable<short> OT7 { get; set; }
        public Nullable<short> OT8 { get; set; }
        public Nullable<short> OT9 { get; set; }
        public Nullable<short> OT10 { get; set; }
        public Nullable<short> OT11 { get; set; }
        public Nullable<short> OT12 { get; set; }
        public Nullable<short> OT13 { get; set; }
        public Nullable<short> OT14 { get; set; }
        public Nullable<short> OT15 { get; set; }
        public Nullable<short> OT16 { get; set; }
        public Nullable<short> OT17 { get; set; }
        public Nullable<short> OT18 { get; set; }
        public Nullable<short> OT19 { get; set; }
        public Nullable<short> OT20 { get; set; }
        public Nullable<short> OT21 { get; set; }
        public Nullable<short> OT22 { get; set; }
        public Nullable<short> OT23 { get; set; }
        public Nullable<short> OT24 { get; set; }
        public Nullable<short> OT25 { get; set; }
        public Nullable<short> OT26 { get; set; }
        public Nullable<short> OT27 { get; set; }
        public Nullable<short> OT28 { get; set; }
        public Nullable<short> OT29 { get; set; }
        public Nullable<short> OT30 { get; set; }
        public Nullable<short> OT31 { get; set; }
        public Nullable<short> AOT1 { get; set; }
        public Nullable<short> AOT2 { get; set; }
        public Nullable<short> AOT3 { get; set; }
        public Nullable<short> AOT4 { get; set; }
        public Nullable<short> AOT5 { get; set; }
        public Nullable<short> AOT6 { get; set; }
        public Nullable<short> AOT7 { get; set; }
        public Nullable<short> AOT8 { get; set; }
        public Nullable<short> AOT9 { get; set; }
        public Nullable<short> AOT10 { get; set; }
        public Nullable<short> AOT11 { get; set; }
        public Nullable<short> AOT12 { get; set; }
        public Nullable<short> AOT13 { get; set; }
        public Nullable<short> AOT14 { get; set; }
        public Nullable<short> AOT15 { get; set; }
        public Nullable<short> AOT16 { get; set; }
        public Nullable<short> AOT17 { get; set; }
        public Nullable<short> AOT18 { get; set; }
        public Nullable<short> AOT19 { get; set; }
        public Nullable<short> AOT20 { get; set; }
        public Nullable<short> AOT21 { get; set; }
        public Nullable<short> AOT22 { get; set; }
        public Nullable<short> AOT23 { get; set; }
        public Nullable<short> AOT24 { get; set; }
        public Nullable<short> AOT25 { get; set; }
        public Nullable<short> AOT26 { get; set; }
        public Nullable<short> AOT27 { get; set; }
        public Nullable<short> AOT28 { get; set; }
        public Nullable<short> AOT29 { get; set; }
        public Nullable<short> AOT30 { get; set; }
        public Nullable<short> AOT31 { get; set; }
        public string ShiftName { get; set; }
        public Nullable<short> AcTotalOT { get; set; }
        public Nullable<short> AppTotalOT { get; set; }
        public Nullable<short> AcGzOT { get; set; }
        public Nullable<short> AppGzOT { get; set; }
        public string S1 { get; set; }
        public string S2 { get; set; }
        public string S3 { get; set; }
        public string S4 { get; set; }
        public string S5 { get; set; }
        public string S6 { get; set; }
        public string S7 { get; set; }
        public string S8 { get; set; }
        public string S9 { get; set; }
        public string S10 { get; set; }
        public string S11 { get; set; }
        public string S12 { get; set; }
        public string S13 { get; set; }
        public string S14 { get; set; }
        public string S15 { get; set; }
        public string S16 { get; set; }
        public string S17 { get; set; }
        public string S18 { get; set; }
        public string S19 { get; set; }
        public string S20 { get; set; }
        public string S21 { get; set; }
        public string S22 { get; set; }
        public string S23 { get; set; }
        public string S24 { get; set; }
        public string S25 { get; set; }
        public string S26 { get; set; }
        public string S27 { get; set; }
        public string S28 { get; set; }
        public string S29 { get; set; }
        public string S30 { get; set; }
        public string S31 { get; set; }
    }
}
