//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmergencyMachine
    {
        public int ID { get; set; }
        public string IP { get; set; }
        public string MachineName { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> InActiveDate { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public Nullable<System.DateTime> LastCheck { get; set; }
        public Nullable<bool> Monitor { get; set; }
        public Nullable<bool> EmailSent { get; set; }
        public Nullable<bool> EmailSentForConnected { get; set; }
    }
}
