//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmergencyEmail
    {
        public int ID { get; set; }
        public string EmailAdd { get; set; }
        public string Message { get; set; }
        public Nullable<bool> ApplicationClose { get; set; }
        public Nullable<bool> MachineClose { get; set; }
        public Nullable<bool> ReaderNotPinged { get; set; }
        public Nullable<bool> OnlyTo { get; set; }
        public Nullable<bool> OnlyCC { get; set; }
    }
}
