//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpViewEmerg
    {
        public string CompName { get; set; }
        public string LocName { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public string CardNo { get; set; }
        public Nullable<bool> Status { get; set; }
        public string SectionName { get; set; }
        public string DivisionName { get; set; }
        public Nullable<short> CompanyID { get; set; }
        public Nullable<short> SecID { get; set; }
        public Nullable<short> LocID { get; set; }
        public int EmpID { get; set; }
        public Nullable<short> CityID { get; set; }
        public short DeptID { get; set; }
        public string DeptName { get; set; }
        public Nullable<short> ReaderID { get; set; }
        public Nullable<System.DateTime> LastEntryDateTime { get; set; }
        public Nullable<bool> IsSafe { get; set; }
        public Nullable<bool> Presence { get; set; }
    }
}
