//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERPAttMonthData
    {
        public int PID { get; set; }
        public string EmpNo { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string Period { get; set; }
        public Nullable<double> PaidDays { get; set; }
        public Nullable<int> SingleOvertimeMin { get; set; }
        public Nullable<int> DoubleOvertimeMin { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<bool> IsUpdate { get; set; }
    }
}
