//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FatimaPayRoll
    {
        public int PID { get; set; }
        public int EmpID { get; set; }
        public string MonthYear { get; set; }
        public Nullable<double> TotalDays { get; set; }
        public Nullable<double> EarnedDays { get; set; }
        public Nullable<double> ApprovedOverTime { get; set; }
        public Nullable<double> AvailedCL { get; set; }
        public Nullable<double> TotalCL { get; set; }
        public Nullable<double> BalanceCL { get; set; }
        public string BadliEmpOne { get; set; }
        public Nullable<double> BadliDaysOne { get; set; }
        public string BadliEmpTwo { get; set; }
        public Nullable<double> BadliDaysTwo { get; set; }
        public string BadliEmpThree { get; set; }
        public Nullable<double> BadliDaysThree { get; set; }
        public string BadliEmpFour { get; set; }
        public Nullable<double> BadliDaysFour { get; set; }
        public string BadliEmpFive { get; set; }
        public Nullable<double> BadliDaysFive { get; set; }
        public string BadliEmpSix { get; set; }
        public Nullable<double> BadliDaysSix { get; set; }
        public Nullable<double> AvailedSL { get; set; }
        public Nullable<double> TotalSL { get; set; }
        public Nullable<double> BalanceSL { get; set; }
        public Nullable<double> AvailedAL { get; set; }
        public Nullable<double> TotalAL { get; set; }
        public Nullable<double> BalanceAL { get; set; }
    }
}
