//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveImport
    {
        public string EmpNo { get; set; }
        public Nullable<double> AL { get; set; }
        public Nullable<double> CL { get; set; }
        public Nullable<double> SL { get; set; }
    }
}
