//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewHSEHour
    {
        public Nullable<short> DeptID { get; set; }
        public Nullable<System.DateTime> HSEDate { get; set; }
        public Nullable<int> MngEmpHours { get; set; }
        public Nullable<int> StaffEmpHours { get; set; }
        public Nullable<int> ContractEmpHour { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> SecID { get; set; }
        public string SecName { get; set; }
        public string DeptName { get; set; }
        public Nullable<int> StaffEmps { get; set; }
        public Nullable<int> MngEmps { get; set; }
        public Nullable<int> ContractEmps { get; set; }
        public int PDID { get; set; }
        public string Type { get; set; }
    }
}
