//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmailSent
    {
        public string SectionName { get; set; }
        public string EmailAddress { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> ID { get; set; }
        public string CCAddress { get; set; }
        public string CriteriaComLoc { get; set; }
        public Nullable<System.DateTime> SendDateTime { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public Nullable<System.DateTime> AttDate { get; set; }
        public int PID { get; set; }
    }
}
