//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAttBadliMonth
    {
        public int PAttID { get; set; }
        public string EmpPeriod { get; set; }
        public string EmpIDB1 { get; set; }
        public Nullable<double> Days1 { get; set; }
        public string EmpIDB2 { get; set; }
        public Nullable<double> Days2 { get; set; }
        public string EmpIDB3 { get; set; }
        public Nullable<double> Days3 { get; set; }
        public string EmpIDB4 { get; set; }
        public Nullable<double> Days4 { get; set; }
        public Nullable<double> Days5 { get; set; }
        public string EmpIDB5 { get; set; }
        public string EmpIDB6 { get; set; }
        public Nullable<double> Days6 { get; set; }
        public string EmpIDB7 { get; set; }
        public Nullable<double> Days7 { get; set; }
        public string EmpIDB8 { get; set; }
        public Nullable<double> Days8 { get; set; }
        public string EmpIDB9 { get; set; }
        public Nullable<double> Days9 { get; set; }
        public string EmpIDB10 { get; set; }
        public Nullable<double> Days10 { get; set; }
        public string DesignationName { get; set; }
        public string GradeName { get; set; }
        public string CompName { get; set; }
        public string JobTitle { get; set; }
        public string CityName { get; set; }
        public string LocName { get; set; }
        public string RegionName { get; set; }
        public string CrewName { get; set; }
        public string TypeName { get; set; }
        public string CatName { get; set; }
        public string ShiftName { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public Nullable<int> DesigID { get; set; }
        public Nullable<short> JobID { get; set; }
        public Nullable<byte> Gender { get; set; }
        public string CardNo { get; set; }
        public Nullable<int> FpID { get; set; }
        public string PinCode { get; set; }
        public string FatherName { get; set; }
        public string NicNo { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string MarStatus { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ResignDate { get; set; }
        public string HomeAdd { get; set; }
        public bool ProcessAtt { get; set; }
        public Nullable<bool> Status { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<short> CompanyID { get; set; }
        public string DivisionName { get; set; }
        public string SectionName { get; set; }
        public Nullable<short> CatID { get; set; }
        public Nullable<short> SecID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<byte> TypeID { get; set; }
        public Nullable<short> LocID { get; set; }
        public Nullable<short> GradeID { get; set; }
        public Nullable<short> CrewID { get; set; }
        public Nullable<short> CityID { get; set; }
        public short DeptID { get; set; }
        public string DeptName { get; set; }
        public short DivID { get; set; }
        public Nullable<int> EmpID { get; set; }
    }
}
