//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFatimaPayroll
    {
        public Nullable<double> TotalDays { get; set; }
        public Nullable<double> EarnedDays { get; set; }
        public Nullable<double> ApprovedOverTime { get; set; }
        public Nullable<double> AvailedCL { get; set; }
        public Nullable<double> TotalCL { get; set; }
        public Nullable<double> BalanceCL { get; set; }
        public string BadliEmpOne { get; set; }
        public Nullable<double> BadliDaysOne { get; set; }
        public string BadliEmpTwo { get; set; }
        public Nullable<double> BadliDaysTwo { get; set; }
        public string BadliEmpThree { get; set; }
        public Nullable<double> BadliDaysThree { get; set; }
        public string BadliEmpFour { get; set; }
        public Nullable<double> BadliDaysFour { get; set; }
        public string BadliEmpFive { get; set; }
        public Nullable<double> BadliDaysFive { get; set; }
        public string BadliEmpSix { get; set; }
        public Nullable<double> BadliDaysSix { get; set; }
        public Nullable<double> AvailedSL { get; set; }
        public Nullable<double> TotalSL { get; set; }
        public Nullable<double> BalanceSL { get; set; }
        public Nullable<double> AvailedAL { get; set; }
        public Nullable<double> TotalAL { get; set; }
        public Nullable<double> BalanceAL { get; set; }
        public string DesignationName { get; set; }
        public string CompName { get; set; }
        public string JobTitle { get; set; }
        public string CityName { get; set; }
        public string RegionName { get; set; }
        public string LocName { get; set; }
        public string CrewName { get; set; }
        public string TypeName { get; set; }
        public string CatName { get; set; }
        public string ShiftName { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public Nullable<int> DesigID { get; set; }
        public Nullable<short> JobID { get; set; }
        public string FatherName { get; set; }
        public Nullable<bool> Status { get; set; }
        public string SectionName { get; set; }
        public string DivisionName { get; set; }
        public Nullable<short> CompanyID { get; set; }
        public Nullable<short> CatID { get; set; }
        public Nullable<short> SecID { get; set; }
        public short DivID { get; set; }
        public string DeptName { get; set; }
        public short DeptID { get; set; }
        public Nullable<short> CityID { get; set; }
        public int Expr1 { get; set; }
        public Nullable<short> CrewID { get; set; }
        public Nullable<short> GradeID { get; set; }
        public Nullable<short> LocID { get; set; }
        public Nullable<byte> TypeID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public int EmpID { get; set; }
        public string GradeName { get; set; }
        public Nullable<byte> Gender { get; set; }
        public string NicNo { get; set; }
        public string MonthYear { get; set; }
    }
}
