//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAttDataEmgr
    {
        public int EmpID { get; set; }
        public Nullable<short> CityID { get; set; }
        public short DeptID { get; set; }
        public string DeptName { get; set; }
        public Nullable<short> ReaderID { get; set; }
        public Nullable<System.DateTime> LastEntryDateTime { get; set; }
        public Nullable<bool> IsSafe { get; set; }
        public Nullable<bool> Presence { get; set; }
        public Nullable<short> SecID { get; set; }
        public Nullable<short> LocID { get; set; }
        public Nullable<short> CompanyID { get; set; }
        public string DivisionName { get; set; }
        public string SectionName { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CardNo { get; set; }
        public string EmpName { get; set; }
        public string EmpNo { get; set; }
        public string LocName { get; set; }
        public string CompName { get; set; }
        public string EmpDate { get; set; }
        public Nullable<System.DateTime> AttDate { get; set; }
        public string DutyCode { get; set; }
        public Nullable<System.TimeSpan> DutyTime { get; set; }
        public Nullable<System.DateTime> TimeIn { get; set; }
        public Nullable<System.DateTime> TimeOut { get; set; }
        public Nullable<short> WorkMin { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Tin0 { get; set; }
        public Nullable<System.DateTime> Tout0 { get; set; }
        public Nullable<System.DateTime> Tin1 { get; set; }
        public Nullable<System.DateTime> Tout1 { get; set; }
        public Nullable<System.DateTime> Tin2 { get; set; }
        public Nullable<System.DateTime> Tout2 { get; set; }
        public Nullable<System.DateTime> Tin3 { get; set; }
        public Nullable<System.DateTime> Tout3 { get; set; }
    }
}
