//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewERPMonthDataPer
    {
        public Nullable<int> EmpID { get; set; }
        public string EmpName { get; set; }
        public string EmpNo { get; set; }
        public string EmpMonth { get; set; }
        public string Period { get; set; }
        public Nullable<byte> TotalDays { get; set; }
        public Nullable<byte> WorkDays { get; set; }
        public Nullable<byte> LeaveDays { get; set; }
        public Nullable<byte> GZDays { get; set; }
        public Nullable<byte> RestDays { get; set; }
        public Nullable<byte> AbDays { get; set; }
        public Nullable<byte> PreDays { get; set; }
        public Nullable<byte> OfficialDutyDays { get; set; }
        public Nullable<short> TEarlyIn { get; set; }
        public Nullable<short> TEarlyOut { get; set; }
        public Nullable<short> TLateIn { get; set; }
        public Nullable<short> TLateOut { get; set; }
        public Nullable<short> TWorkTime { get; set; }
        public Nullable<short> TNOT { get; set; }
        public Nullable<short> TGZOT { get; set; }
        public Nullable<short> ExpectedWrkTime { get; set; }
        public Nullable<short> CompanyID { get; set; }
    }
}
