//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAttDataOT
    {
        public string EmpDate { get; set; }
        public Nullable<System.DateTime> AttDate { get; set; }
        public Nullable<System.DateTime> Tin1 { get; set; }
        public Nullable<System.DateTime> Tout1 { get; set; }
        public Nullable<System.DateTime> Tin2 { get; set; }
        public Nullable<System.DateTime> Tout2 { get; set; }
        public Nullable<System.DateTime> Tin3 { get; set; }
        public Nullable<System.DateTime> Tout3 { get; set; }
        public Nullable<short> Mins { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public string CompName { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string SectionName { get; set; }
        public string DesignationName { get; set; }
        public string ShiftName { get; set; }
        public string FatherName { get; set; }
        public string DeptName { get; set; }
        public Nullable<int> DesigID { get; set; }
        public Nullable<short> CompanyID { get; set; }
        public Nullable<short> SecID { get; set; }
        public Nullable<short> DeptID { get; set; }
        public Nullable<System.DateTime> ETin1 { get; set; }
        public Nullable<System.DateTime> ETout1 { get; set; }
        public Nullable<System.DateTime> ETin2 { get; set; }
        public Nullable<System.DateTime> ETout2 { get; set; }
        public Nullable<System.DateTime> ETin3 { get; set; }
        public Nullable<System.DateTime> ETout3 { get; set; }
        public string Remarks { get; set; }
    }
}
