//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewJobCardAudit
    {
        public string DesignationName { get; set; }
        public string CompName { get; set; }
        public string JobTitle { get; set; }
        public string CityName { get; set; }
        public string RegionName { get; set; }
        public string LocName { get; set; }
        public string CrewName { get; set; }
        public string CatName { get; set; }
        public string ShiftName { get; set; }
        public string EmpNo { get; set; }
        public string EmpName { get; set; }
        public Nullable<int> DesigID { get; set; }
        public Nullable<short> JobID { get; set; }
        public string GradeName { get; set; }
        public string SectionName { get; set; }
        public string DivisionName { get; set; }
        public Nullable<short> CompanyID { get; set; }
        public Nullable<short> CatID { get; set; }
        public Nullable<short> SecID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public Nullable<byte> TypeID { get; set; }
        public Nullable<short> LocID { get; set; }
        public Nullable<short> GradeID { get; set; }
        public Nullable<short> CrewID { get; set; }
        public Nullable<short> CityID { get; set; }
        public Nullable<short> DeptID { get; set; }
        public string DeptName { get; set; }
        public Nullable<short> DivID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<System.DateTime> DateEnded { get; set; }
        public string JobCardCriteria { get; set; }
        public Nullable<int> CriteriaData { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Remarks { get; set; }
        public int JobCardID { get; set; }
        public string WorkCardName { get; set; }
        public Nullable<bool> NormalWork { get; set; }
        public Nullable<bool> OverTime { get; set; }
        public Nullable<short> WorkMin { get; set; }
        public Nullable<bool> WorkMinEnable { get; set; }
        public string DutyCodeID { get; set; }
        public Nullable<short> Expr1 { get; set; }
        public short WorkCardID { get; set; }
        public string UserName { get; set; }
        public int Expr2 { get; set; }
    }
}
