//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewHSCTest
    {
        public Nullable<short> DeptID { get; set; }
        public string DeptName { get; set; }
        public Nullable<short> SecID { get; set; }
        public string SectionName { get; set; }
        public Nullable<int> TotalMins { get; set; }
        public Nullable<int> Tot { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> AttDate { get; set; }
    }
}
